name: Dependency review

on:
  pull_request:

permissions:
  contents: read

jobs:
  dependency-review:
    name: Dependency review
    uses: abijith-suresh/workflows/.github/workflows/dependency-review.yml@0f257b2642d2a010fefe0ff9d03374799d73eb44 # central workflows v0.3.0
    with:
      fail-on-severity: high
    permissions:
      contents: read
